### PR TITLE
use github servers instead of openwrts

### PR DESCRIPTION
**Pull request by aparcar**
snippets: automatically create all repositories

### CODE REVIEW

**Comment by aparcar** [comment]
@p4u

**Comment by aparcar** [comment]
@G10h4ck

**Comment by nicopace** [comment]
is there a reason that motivates this change?
If ain't broken, don't fix it? :)

**Comment by aparcar** [comment]
@nicopace It's kinda broken for the new CI. I want to dynamically add targets without having to fiddle with the cooker default targets. Anyway, I fixed it by not using the cooker which simplifies the whole setup.

**Comment by nicopace** [comment]
What is in cooker that is broken? it is important not to be broken, as it is the tool everyone uses!
@aparcar Could you report that issue in https://github.com/libremesh/lime-sdk ?

**Comment by aparcar** [comment]
It's broken for the CI case, at least when I tried the openwrt servers started to block the cooker from downloading source from git.openwrt.org, thats why I created the previous PR.

Currently the cooker does not automatically replace outdated snapshot builds, also likely a special CI case.

**Pull request closed without merging**
