### PR TITLE
build luci-app-bmx7

### PR DESCRIPTION
**Pull request by aparcar**
this app is not build by default and so not installable via cooker

### CODE REVIEW

**Comment by aparcar** [comment]
@p4u please merge and re-run cooker

**Review by p4u — COMMENTED** [review]
wrong syntax

**Comment by aparcar** [comment]
merci

**Comment by aparcar** [comment]
@p4u I still can't find the package here:
https://downloads.libremesh.org/current/packages/x86_64/routing/

**Pull request merged**
