### PR TITLE
Adds exit code for cooking.

### PR DESCRIPTION
**Pull request by nicopace**
Solves #13

### CODE REVIEW

**Comment by nicopace** [comment]
Tested in my computer and returns 0 for successful builds.
Any idea how to make a build fail?

**Comment by ilario** [comment]
This is a good solution but works just when cooking, right?
If other functions of the software are called, the exit code will be always 0 even if they fail?

**Comment by p4u** [comment]
Ilario is right, if the code returns 1 when cooking fails, at least the build_sdk function should also return 1 in case of fail (for consistency).

However it might be implemented later on.

**Comment by ilario** [comment]
I filed an issue for tracking the implementation of exit codes for the other functions in cooker: #16.

**Pull request merged**
