### PR TITLE
setup travis builds develop branch

### PR DESCRIPTION
**Pull request by aparcar**

### CODE REVIEW

**Comment by aparcar** [comment]
@nicopace ping

**Comment by nicopace** [comment]
The only difference between this one and the one on master is the BRANCH=develop line.
Can't we merge this two?
I don't like the differences between develop and master... master should be a pointer to a state of the develop branch... right?

**Review by ilario — APPROVED** [review]
Travis file is just the same as in Master branch: ok.
Dockerfile has just the difference pointed by @nicopace : the develop label instead of the master one. For me it is not a problem to have such kind of differences 'cause we're not talking about our code, that gets developed in develop and merged in master. Instead we're talking about an external service building images of master and of develop (please correct me if I'm wrong), so having differences is ok.

**Comment by nicopace** [comment]
@ilario I was just saying that those variables can be asked to the git command: `git branch | grep \* | cut -d ' ' -f2`

**Pull request merged**
