### PR TITLE
feeds: use github mirror to enable CI

### PR DESCRIPTION
**Pull request by aparcar**
CI (travis) is seems quickly blocked by travis

### CODE REVIEW

**Comment by aparcar** [comment]
@nicopace required for further CI fun

**Comment by nicopace** [comment]
@p4u @G10h4ck ?
We loose autonomacy, but I guess we will always have openwrt ;)

**Comment by aparcar** [comment]
I could add a CI var which automatically changes the sources if used as CI

**Comment by aparcar** [comment]
https://github.com/libremesh/lime-sdk/pull/65 this seems better

**Pull request closed without merging**
