### PR TITLE
Added Luci2 (luci-ng) packages and flavor.

### PR DESCRIPTION
**Pull request by gmarcos87**
Add the option to compile with Luci2 packages for development and testing purposes.

### CODE REVIEW

**Comment by p4u** [comment]
Currently it seems that luci2 cross compilation needs NodeJS and other stuff which might be better, until it is not mandatory, to avoid it. So I propose to merge this pull request on a separate branch. So users who do not need to develop over Luci2 won't need to compile all the stuff.

**Comment by gmarcos87** [comment]
@p4u It makes sense, is a problem to solve that luci-ng should download and compile node in addition to download all other tools and dependencies via npm. Maybe we should make a package that already contains the build of static files (js, html, etc) and publish them as an alternative to luci2-ui-base.

**Comment by p4u** [comment]
@gmarcos87 I created the branch luci2, you can send the PR there and keep the development of this on this branch until it is mature enough to merge it with master.

**Comment by nicopace** [comment]
@gmarcos87 @p4u can we close the issue then?

**Pull request merged**
